<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
 "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>net.activitywatch.aw-watcher-network</string>

  <key>ProgramArguments</key>
  <array>
    <string>/usr/local/bin/aw-watcher-network</string>
    <string>--config</string>
    <string>/Users/username/.config/activitywatch/aw-watcher-network-config.yaml</string>
  </array>

  <key>RunAtLoad</key>
  <true/>

  <key>KeepAlive</key>
  <true/>

  <key>StandardOutPath</key>
  <string>/tmp/aw-watcher-network.out</string>
  <key>StandardErrorPath</key>
  <string>/tmp/aw-watcher-network.err</string>
</dict>
</plist>
